<p>
    im Folgenden bitten wir um die Abnahme der wie vereinbar erbrachten Leistungen.
</p>
<? echoIf($description, '%v') ?>
<p>Wir hoffen, unsere Arbeit entspricht Ihren Vorstellungen.
    Für Rückfragen stehen wir Ihnen natürlich gerne unter
    <? echoIf($conf['mail']['replyto'], '<a href="mailto:%v">%v</a>') ?> zur Verfügung.
</p>
<p>
    Mit freundlichen Grüßen,
</p>
<p class="colored">
    <?= $conf['company'] ?>
</p>

<? pageBreak() ?>

<p class="heading"><?=$name ?></p>
<table class="table">
    <thead>
    <tr>
        <th class="left">
            Posten
        </th>
        <th width="10%">
            Abgenommen
        </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($items['list'] as $item) { ?>
        <tr>
            <td class="left">
                <span class="big"><?= $item['name'] ?></span>
                <? echoIf($item['description'], '<br/>%v') ?>
            </td>
            <td width="10%">
                &nbsp;
            </td>
        </tr>
    <?php } ?>
    <tr class="total">
        <td class="right">
            Alle aufgelisteten Leistungen
        </td>
        <td width="10%">
            &nbsp;
        </td>
    </tr>
    </tbody>
</table>
<br/>
<p class="less">
    Durch Ankreuzen der entsprechenden Leistung und Ihre Unterschrift nehmen Sie die angekreuzten Leistungen
    <?php if ($conf['pricing']['hint_agb']) { ?>
    im Sinne unserer AGB
    <?php } ?>
    ab, akzeptieren sie somit als erfolgreich, wunsch- und vereinbarungsgemäß erbracht
    und erklären sich damit einverstanden, die Rechnung über ebenjene Posten, die Ihnen demnächst zugestellt wird,
    in voller Höhe binnen Frist zu begleichen.
</p>
<br/>
<p>
    Hiermit erkläre ich die angekreuzten Leistungen für abgenommen.
</p>
<table class="signature">
    <tr>
        <td width="33%">

        </td>
        <td>

        </td>
        <td width="33%">
            <?php
            echoIf($project['client']['contact_firstname'],'%v ');
            echoIf($project['client']['contact_lastname']);
            echoIf($project['client']['companyname'],'<br/>%v<br/>');
            ?>
        </td>
    </tr>
    <tr>
        <td width="33%" class="signeline">

        </td>
        <td>

        </td>
        <td width="33%"  class="signeline">

        </td>
    </tr>
    <tr>
        <td width="33%">
            Datum, Ort
        </td>
        <td>

        </td>
        <td width="33%">
            Unterschrift
        </td>
    </tr>
</table>


