<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Test 123</title>
    <link href='http://fonts.googleapis.com/css?family=Poiret+One&v2' rel='stylesheet' type='text/css'>
    <style type="text/css">
        h1, p
        {
            font-weight: normal;
            font-family: 'Poiret One';
        }
        @page { margin: 180px 50px; }
        #header { position: fixed; left: 0px; top: -180px; right: 0px; height: 150px; background-color: orange; text-align: center; }
        #footer { position: fixed; left: 0px; bottom: -180px; right: 0px; height: 150px; background-color: lightblue; }
        #footer .page:after { content: counter(page, upper-roman); }
    </style>
</head>
<body>

<div id="header">
    <h1>Widgets Express</h1>
</div>
<div id="footer">
    <p class="page">Page </p>
</div>
<div id="content">
    <p>the first page</p>
    <p style="page-break-before: always;">the second page</p>
</div>
<p><?=$name ?></p>
</body>
</html>