<p>Sie erhalten heute wie gewünscht Ihr Angebot mit der Referenznummer <?= $refnumber ?> zum Thema "<?= $name ?>".</p>
<? echoIf($description, '%v') ?>
<p>TODO</p>

<? pageBreak() ?>

<p class="heading"><?=$name ?></p>

<table class="table">
    <thead>
        <tr>
            <th width="70%" class="left">

                    Posten

            </th>
            <th width="20%" class="right">

                    Kosten

            </th>
            <th width="10%" class="center">

                    Auftrag

            </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($items['list'] as $item) { ?>
        <tr>
            <td width="70%" class="left">

                    <span class="big"><?= $item['name'] ?></span>
                    <? echoIf($item['description'], '<br/>%v') ?>

            </td>
            <td width="20%" class="right">

                    <?= $item['total'] ?>

            </td>
            <td width="10%" class="center">


            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>



<p>Gesamt:</p>
<p>
    Vorsteuer:<?= $items['costs']['beforetax'] ?><br/>
    Steuer:<?= $items['costs']['tax'] ?><br/>
    Gesamt:<?= $items['costs']['total'] ?>
</p>


<?php //echo var_dump($items) ?>

