<p>
    wir konnten für die Rechnung <?= $invoice['refnumber']; ?> vom <?= formatDate($invoice['date']) ?> über
    <?= twodec($invoice['items']->costs['total']) ?> €, fällig am <?= formatDate($invoice['duedate']) ?>,
    noch keinen Zahlungseingang feststellen.
</p>

<? echoIf($description, '%v') ?>

<p>Bitte überweisen Sie den Rechnungsbetrag unter Angabe der Rechnungsnummer
    binnen der nächsten drei Werktage auf folgendes Konto:</p>

<table>
    <tr>
        <td width="20%">Kontoinhaber:</td>
        <td><?= $conf['account']['owner'] ?></td>
    </tr>
    <tr>
        <td width="20%">Bank:</td>
        <td><?= $conf['account']['bank'] ?></td>
    </tr>
    <tr>
        <td width="20%">IBAN:</td>
        <td><?= $conf['account']['IBAN'] ?></td>
    </tr>
    <tr>
        <td width="20%">BIC:</td>
        <td><?= $conf['account']['BIC'] ?></td>
    </tr>
</table>
<br/>


<p>
    Für Rückfragen stehen wir Ihnen natürlich gerne unter
    <? echoIf($conf['mail']['replyto'], '<a href="mailto:%v">%v</a>') ?> zur Verfügung.
</p>
<p>
    Mit freundlichen Grüßen,
</p>
<p class="colored">
    <?= $conf['company'] ?>
</p>
