<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Test 123</title>
    <link href='http://fonts.googleapis.com/css?family=Poiret+One&v2' rel='stylesheet' type='text/css'>
    <style type="text/css">
        h1, p
        {
            font-weight: normal;
            font-family: 'Poiret One';
        }
    </style>
</head>
<body>
<h1>Test 12</h1>
<p>This is a hello world example of an xhtml template that shall be converted to pdf!</p>
<p><?=$name ?></p>
</body>
</html>