<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
</head>

<body bgcolor="#F2F2F2">
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#F2F2F2">
    <tr>
        <td><table width="600" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF" align="center" >
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td align="right" style="color:<?= $design["color"] ?>; font-size: 28px; font-family: Arial, Helvetica, sans-serif;">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="10%">&nbsp;</td>
                                <td width="80%" align="right" valign="top">
                                    <span style="font-family: Arial, Helvetica, sans-serif; color:#333333; font-size:13px; line-height:21px">
                                            <img src="<?= $design["logo"] ?>" alt="<?= $company ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"/>
                                    </span>
                                </td>
                                <td width="10%">&nbsp;</td>
                            </tr>

                        </table>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td bgcolor="<?= $design["color"] ?>" height="3" style="line-height: 3px;">&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="10%">&nbsp;</td>
                                <td width="80%" align="left" valign="top">
                                    <span style="font-family: Arial, Helvetica, sans-serif; color:#333333; font-size:13px; line-height:21px">

                                            <?= $content ?>


                                    </span>
                                </td>
                                <td width="10%">&nbsp;</td>
                            </tr>

                        </table>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <!-- Color bar -->
                <tr>
                    <td bgcolor="<?= $design["color"]?>" height="25" style="line-height: 25px;">&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td align="center">
                        <span style="font-family:Arial, sans-serif; color:#666666; font-size:10px">
                            <b><?= $company ?><br/>
                            <? echoIf($company_addition, '%v<br/>') ?>
                            </b>
                            <? echoIf($address["street"], '%v<br/>') ?>
                            <? echoIf($address["zip"]) ?>
                            <? echoIf($address["city"], '%v<br/>') ?>
                            <? echoIf($address["country"], '%v<br/>') ?>
                            <br/>
                            <? echoIf($address["telephone"], 'Tel.: %v<br/>') ?>
                            <? echoIf($address["fax"], 'Fax: %v<br/>') ?>
                            <? echoIf($mail["replyto"], 'Mail: <a href="mailto:%v">%v</a><br/>') ?>
                            <? echoIf($address["web"], 'Web: <a href="%v">%v</a><br/>') ?>


                        </span>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
            </table></td>
    </tr>
</table>
</body>
</html>
