<?php

if(exists($project['client']['contact_lastname']) && $project['client']['contact_gender'] == 'm')
{
    $anrede = 'Sehr geehrter Herr '.$project['client']['contact_lastname'];
}
else if (exists($project['client']['contact_lastname']) && $project['client']['contact_gender'] == 'f')
{
    $anrede = 'Sehr geehrte Frau '.$project['client']['contact_lastname'];
}
else
{
    $anrede = 'Sehr geehrte Damen und Herren';
}
?>

<?= $anrede ?>, <br/>
    <br/>
    wir bitten Sie heute um die Abnahme <?= $refnumber ?> der von uns erbrachten Leistungen.<br/>
    Wir hoffen, Sie sind mit unseren Leistungen zufrieden und freuen uns auf weitere Zusammenarbeit.<br/>
    <br/>
<? echoIf($additional, '%v<br/><br/>') ?>
    Mit freundlichen Grüßen,<br/>
<?= $company ?><br/>
<? echoIf($company_addition, '%v<br/>') ?>