<?php

if(exists($project['client']['contact_lastname']) && $project['client']['contact_gender'] == 'm')
{
    $anrede = 'Sehr geehrter Herr '.$project['client']['contact_lastname'];
}
else if (exists($project['client']['contact_lastname']) && $project['client']['contact_gender'] == 'f')
{
    $anrede = 'Sehr geehrte Frau '.$project['client']['contact_lastname'];
}
else
{
    $anrede = 'Sehr geehrte Damen und Herren';
}

?>

<?= $anrede ?>, <br/>
    <br/>
    Sie erhalten heute eine Zahlungserinnerung (<?= $refnumber ?>) für Ihre Rechnung <?= $invoice['refnumber'] ?> vom <?= formatDate($invoice['date']) ?>.<br/>
    Wir konnten bis jetzt keinen Zahlungseingang feststellen und bitten Sie, dies binnen 3 Werktagen nachzuholen.<br/>
    Sollte dies ein Irrtum sein, kontaktieren Sie uns bitte.<br/>
    <br/>
<? echoIf($additional, '%v<br/><br/>') ?>
    Mit freundlichen Grüßen,<br/>
<?= $company ?><br/>
<? echoIf($company_addition, '%v<br/>') ?>